apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.observer.metricServer.nameOverride }}
  namespace: {{ .Release.Namespace }} 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.observer.metricServer.nameOverride }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.observer.metricServer.nameOverride }}
    spec:
      containers:
        - command:
            - observer-metric-server
          image: {{ .Values.observer.metricServer.image.serverImage }}
          imagePullPolicy: {{ .Values.observer.metricServer.image.pullPolicy }}
          name: server
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "echo 'hello'|nc local:/var/run/observer.sock"]
          resources:
          {{ toYaml .Values.observer.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run
              name: sock-volume
        - command:
            - observer
          image: {{ .Values.observer.metricServer.image.observerImage }}
          imagePullPolicy: {{ .Values.observer.metricServer.image.pullPolicy }}
          name: obi-controller
          resources:
          {{ toYaml .Values.observer.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run
              name: sock-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: {{ .Values.observer.serviceAccountName }}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: sock-volume
