apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.executor.nameOverride }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: executor
rules:
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - observabilityactionpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - observabilityactionpolicies/finalizers
    verbs:
      - update
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - observabilityactionpolicies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - observabilityindicants
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - observabilityindicants/finalizers
    verbs:
      - update
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - observabilityindicants/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - resourcetaggingpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - resourcetaggingpolicies/finalizers
    verbs:
      - update
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - resourcetaggingpolicies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - resourcetaggings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - resourcetaggings/finalizers
    verbs:
      - update
  - apiGroups:
      - arbiter.k8s.com.cn
    resources:
      - resourcetaggings/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "nodes"
      - "configmaps"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: executor
subjects:
  - kind: ServiceAccount
    name: {{ .Values.executor.nameOverride }}
    namespace: {{ .Release.Namespace }}
---
# executor-default-plugins rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: executor-default-plugins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.executor.nameOverride }}
    namespace: {{ .Release.Namespace }}
