---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: observabilityactionpolicies.arbiter.k8s.com.cn
spec:
  group: arbiter.k8s.com.cn
  names:
    kind: ObservabilityActionPolicy
    listKind: ObservabilityActionPolicyList
    plural: observabilityactionpolicies
    shortNames:
    - oap
    singular: observabilityactionpolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ObservabilityActionPolicy is the Schema for the ObservabilityActionpolicies
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ObservabilityActionPolicySpec defines the desired state of
              ObservabilityActionPolicy
            properties:
              action:
                type: string
              actionData:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              condition:
                description: ActionCondition is the condition for the action
                properties:
                  expression:
                    type: string
                  operator:
                    type: string
                  targetValue:
                    type: string
                type: object
              obIndicantname:
                description: ObIndicantName is the name of a ObservabilityIndicant.
                type: string
            type: object
          status:
            description: ObservabilityActionPolicyStatus defines the observed state
              of ObservabilityActionPolicy
            properties:
              actionInfo:
                description: Names of the updated resources
                items:
                  description: ActionInfo is the information to identify whether a
                    resource is updated
                  properties:
                    conditionValue:
                      type: string
                    expressionValue:
                      type: string
                    resourceName:
                      description: ResourceName is the name of the pod
                      type: string
                  type: object
                type: array
              timeInfo:
                description: ObservabilityTimeInfo defines the observed time range
                  of ObservabilityIndicant
                properties:
                  endTime:
                    format: date-time
                    type: string
                  metricIntervalSeconds:
                    format: int64
                    type: integer
                  startTime:
                    format: date-time
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
