apiVersion: v2
name: arbiter
description: Arbiter is an observing and managing tool for Kubernetes
type: application
version: 0.1.0
icon: https://avatars.githubusercontent.com/u/100769167
appVersion: v0.1.0
keywords:
  - observing
  - arbiter
home: https://arbiter.k8s.com.cn
sources:
  - https://github.com/kube-arbiter/arbiter
maintainers:
  - name: nkwangleiGIT
    url: https://github.com/nkwangleiGIT
  - name: Abirdcfly
    url: https://github.com/Abirdcfly
  - name: 0xff-dev
    url: https://github.com/0xff-dev
