apiVersion: arbiter.k8s.com.cn/v1alpha1
kind: ObservabilityActionPolicy
metadata:
  name: metric-server-node-mem
spec:
  condition:
    expression: avg([metrics.memory])/1000000
    operator: '>='
    targetValue: "0"
  obIndicantname: metric-server-node-mem
  actionData:
    labels:
      memory-sensitive: "true"
      metric-server-node-mem: metric-server
status:
  actionInfo: []
  timeInfo:
    startTime: "2022-09-26T10:46:25Z"
    endTime: "2022-09-26T10:46:25Z"
    metricIntervalSeconds: 15
