apiVersion: arbiter.k8s.com.cn/v1alpha1
kind: ObservabilityActionPolicy
metadata:
  name: prometheus-node-cpu
spec:
  condition:
    expression: avg([metrics.cpu])
    operator: '>='
    targetValue: "0"
  obIndicantname: prometheus-node-cpu
  actionData:
    labels:
      cpu-sensitive: "true"
      prometheus-node-cpu: prometheus
status:
  actionInfo: []
  timeInfo:
    startTime: "2022-09-26T10:46:25Z"
    endTime: "2022-09-26T10:46:25Z"
    metricIntervalSeconds: 15
